// eslint.config.js ─ ESLint 9 (flat)
import antfu from "@antfu/eslint-config";
import eslintJs from "@eslint/js";
import eslintConfigPrettier from "eslint-config-prettier/flat";
import prettierPlugin from "eslint-plugin-prettier";
import vuePlugin from "eslint-plugin-vue";
import globals from "globals";
import tseslint from "typescript-eslint";
import vueParser from "vue-eslint-parser";

import autoImports from "./.eslintrc-auto-import.json" with {type: "json"}; // ⭢ generated by unplugin-auto-import

export default antfu({
	/* ── Antfu baseline ─────────────────────────────────── */
	root: true,
	env: {browser: true, node: true, es2021: true},
	typescript: true,
	vue: true,
	stylistic: {indent: "tab", quotes: "double", semi: true, linebreak: "unix"},
	ignores: ["node_modules/**", "dist/**"],
})
/* ── Shared preset bundles ───────────────────────────── */
.append(
	eslintJs.configs.recommended,
	tseslint.configs.recommended,
	...vuePlugin.configs["flat/essential"],
)

/* ── Project-wide glue / rule tweaks ─────────────────── */
.append({
	languageOptions: {
		globals: {...globals.browser, ...autoImports.globals},
	},
	plugins: {prettier: prettierPlugin},
	
	rules: {
		/* Prettier integration */
		"prettier/prettier": "error",
		
		/* ←── the 3 rules you asked to silence ───────────── */
		"vue/multi-word-component-names": "off",
		"ts/no-explicit-any": "off",
		"no-console": "off",
		
		/* already-disabled style rules that clash with Prettier */
		"style/indent": "off",
		"style/comma-dangle": "off",
		"style/operator-linebreak": "off",
		"antfu/if-newline": "off",
		
		/* we rely on auto-imports instead of no-undef */
		"no-undef": "off",
	},
})

/* ── Per-file language details ───────────────────────── */
.append(
	/* TypeScript ---------------------------------------- */
	{
		files: ["**/*.ts"],
		languageOptions: {
			parser: tseslint.parser,
			parserOptions: {project: "./tsconfig.json"},
			globals: {...globals.node, ...autoImports.globals},
		},
	},
	
	/* Vue SFCs (<script setup>) ------------------------- */
	{
		files: ["**/*.vue"],
		languageOptions: {
			parser: vueParser,
			parserOptions: {
				parser: tseslint.parser,
				extraFileExtensions: [".vue"],
			},
		},
		plugins: {vue: vuePlugin},
		rules: {"vue/no-unused-vars": "off"},
	},
	
	/* Plain JS & build scripts -------------------------- */
	{
		files: ["**/*.{js,cjs,mjs}", "*.config.js", "vite.config.{js,ts}"],
		languageOptions: {sourceType: "module"},
	},
)

/* ── Always keep Prettier conflict killer last ──────── */
.append(eslintConfigPrettier);
