/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module "vue" {
  export interface GlobalComponents {
	  AccountManagement: (typeof import"./components/AccountManagement.vue"")"
	  default;
	  "t;"
	  ];
	  AdminProfile: (typeof imp
	  "./components/AdminProfile.vue";
	  vu;
	  "default";
	  a;
	  ult;
	  "];;;;;
	  ProfileFields: (typeof
	  "./components/ProfileFields.vue";
	  ds;
	  "default";
	  d;
	  efault;
	  "];;;;;
	  README: (type
	  "./components/README.md";
	  RE;
	  "default"
	  );
	  ["default"];
	  RouterLink: (t
	  "";
	  RouterLink;
	  ");[";
	  RouterLink;
	  "];RouterView:";
	  vue
	  -
	  router;
	  ";;;;
	  or;
	  "RouterView";
	  r;
	  "))[";
	  RouterView;
	  "];TheCount;;;;
	  "./components/TheCounter.vue";
	  nt;
	  "default";
	  t;
	  ervue
	  .
	  "))[";
	  default;
	  "];TheF;;;;
	  "./components/TheFooter.vue";
	  po;
	  "default";
	  F;
	  ootervue
	  .
	  "))[";
	  default;
	  "];T;;;;
	  "./components/TheHeader.vue";
	  co;
	  "default";
	  T;
	  heHeadervue
	  .
	  "))[";
	  default;
	  "];";
	  ";;;;
	  default;
	  "n;ts/TheInput.vue";
	  ["default"];
	  "./components/TutorProfile.vue"
	  ))
	  ".";
	  default;
	  "t;s/TutorProfile.vue";
	  ["default"];
	  "./components/UserProfile.vue"
	  ))
	  or;
	  "default";
	  o;
	  nentsUserProfilevue
	  /
	  "))["
	  .
	  defau;
	  "./components/UserSignup.vue";
	  i;
	  "default";
	  c;
	  omponentsUserSignupvue
	  /
	  "))["
	  .
	  default;
	  "];;;;;

	  "vue-router"(

	  "./components/TheInput.vue"(
  }
}
