/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccessibleDialog: typeof import('./components/AccessibleDialog.vue')['default']
    AccessModeToggle: typeof import('./components/AccessModeToggle.vue')['default']
    AccountCodeIdeWorkspace: typeof import('./components/AccountCodeIdeWorkspace.vue')['default']
    AccountManagement: typeof import('./components/AccountManagement.vue')['default']
    AccountSecurity: typeof import('./components/AccountSecurity.vue')['default']
    AdminProfile: typeof import('./components/AdminProfile.vue')['default']
    AdminReviewStatus: typeof import('./components/AdminReviewStatus.vue')['default']
    AdminWorkspaceShell: typeof import('./components/AdminWorkspaceShell.vue')['default']
    CodeIdeWorkspace: typeof import('./components/CodeIdeWorkspace.vue')['default']
    CodePreview: typeof import('./components/CodePreview.vue')['default']
    CourseAccessCodeManager: typeof import('./components/CourseAccessCodeManager.vue')['default']
    CourseAssetPreview: typeof import('./components/CourseAssetPreview.vue')['default']
    CourseAssignmentContent: typeof import('./components/CourseAssignmentContent.vue')['default']
    CourseCodeAccessForm: typeof import('./components/CourseCodeAccessForm.vue')['default']
    CourseExplorer: typeof import('./components/CourseExplorer.vue')['default']
    GraphSketcherWorkspace: typeof import('./components/GraphSketcherWorkspace.vue')['default']
    IdeDiagnosticsControls: typeof import('./components/IdeDiagnosticsControls.vue')['default']
    IdeEnvironmentSelect: typeof import('./components/IdeEnvironmentSelect.vue')['default']
    IdeStarterPicker: typeof import('./components/IdeStarterPicker.vue')['default']
    LazyMarkdownContent: typeof import('./components/LazyMarkdownContent.vue')['default']
    LearnerCodeReviewTools: typeof import('./components/LearnerCodeReviewTools.vue')['default']
    LearnerCourseAccess: typeof import('./components/LearnerCourseAccess.vue')['default']
    LearnerCourseProgressEditor: typeof import('./components/LearnerCourseProgressEditor.vue')['default']
    LearnerSessionTools: typeof import('./components/LearnerSessionTools.vue')['default']
    LearnerWorkspace: typeof import('./components/LearnerWorkspace.vue')['default']
    ProfileDetailsCard: typeof import('./components/ProfileDetailsCard.vue')['default']
    ProfileFields: typeof import('./components/ProfileFields.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScratchIdeWorkspace: typeof import('./components/ScratchIdeWorkspace.vue')['default']
    SelfAccountSettings: typeof import('./components/SelfAccountSettings.vue')['default']
    SessionNoteEvidenceReview: typeof import('./components/SessionNoteEvidenceReview.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    TutorProfile: typeof import('./components/TutorProfile.vue')['default']
    UserCommunicationPanel: typeof import('./components/UserCommunicationPanel.vue')['default']
    UserProfile: typeof import('./components/UserProfile.vue')['default']
    WorkspaceDisclosure: typeof import('./components/WorkspaceDisclosure.vue')['default']
    WorkspaceHeader: typeof import('./components/WorkspaceHeader.vue')['default']
    WorkspaceStorageStatus: typeof import('./components/WorkspaceStorageStatus.vue')['default']
    WorkspaceViewToggle: typeof import('./components/WorkspaceViewToggle.vue')['default']
  }
}
