let mock = [
  {
    id: 1,
    name: "Albert Eggbert",
    email: "fetch@fetcher.com",
    age: 77,
    gender: "Male",
    city: "Aurora",
    state: "CO",
    editTutors: false,
    saveEdit: "Edit",
  },
  {
    id: 2,
    name: "Jannick Válter",
    email: "jan@hotmail.gov",
    age: 25,
    gender: "Male",
    city: "Greensboro",
    state: "NC",
    editTutors: false,
    saveEdit: "Edit",
  },
  {
    id: 3,
    name: "Brenda Guzman",
    email: "guz212@gmail.com",
    age: 20,
    gender: "Female",
    city: "Sunnyvale",
    state: "CA",
    editTutors: false,
    saveEdit: "Edit",
  },
  {
    id: 4,
    name: "Christie Scott",
    email: "pandalover@gmail.org",
    age: 35,
    gender: "Female",
    city: "Tuscaloosa",
    state: "AL",
    editTutors: false,
    saveEdit: "Edit",
  },
  {
    id: 5,
    name: "Darrel Green",
    email: "12345@hotmail.com",
    age: 13,
    gender: "Male",
    city: "Alpharetta",
    state: "GA",
    editTutors: false,
    saveEdit: "Edit",
  },
  {
    id: 6,
    name: "Stella Marshall",
    email: "fetch@fetcher.com",
    age: 37,
    gender: "Male",
    city: "Victorville",
    state: "CA",
    editTutors: false,
    saveEdit: "Edit",
  },
];

export default mock;
