/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/about': RouteRecordInfo<
      '/about',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/': RouteRecordInfo<
      '/admin/',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/mdmail': RouteRecordInfo<
      '/admin/mdmail',
      '/admin/mdmail',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/people': RouteRecordInfo<
      '/admin/people',
      '/admin/people',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/student-management': RouteRecordInfo<
      '/admin/student-management',
      '/admin/student-management',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bluej': RouteRecordInfo<
      '/bluej',
      '/bluej',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/coding_standard': RouteRecordInfo<
      '/coding_standard',
      '/coding_standard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/course-resource': RouteRecordInfo<
      '/course-resource',
      '/course-resource',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/courses': RouteRecordInfo<
      '/courses',
      '/courses',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/graph-sketcher': RouteRecordInfo<
      '/graph-sketcher',
      '/graph-sketcher',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ide': RouteRecordInfo<
      '/ide',
      '/ide',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/pathways': RouteRecordInfo<
      '/pathways',
      '/pathways',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/payment': RouteRecordInfo<
      '/payment',
      '/payment',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/profile': RouteRecordInfo<
      '/profile',
      '/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/python-ide': RouteRecordInfo<
      '/python-ide',
      '/python-ide',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/README': RouteRecordInfo<
      '/README',
      '/README',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/reset-password': RouteRecordInfo<
      '/reset-password',
      '/reset-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/signup': RouteRecordInfo<
      '/signup',
      '/signup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/teaching': RouteRecordInfo<
      '/teaching',
      '/teaching',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/wheel': RouteRecordInfo<
      '/wheel',
      '/wheel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/zelle': RouteRecordInfo<
      '/zelle',
      '/zelle',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/zoom': RouteRecordInfo<
      '/zoom',
      '/zoom',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
      pathParamNames:
        | 'all'
    }
    'src/pages/about.vue': {
      routes:
        | '/about'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/index.vue': {
      routes:
        | '/admin/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/mdmail.vue': {
      routes:
        | '/admin/mdmail'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/people.vue': {
      routes:
        | '/admin/people'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/student-management.vue': {
      routes:
        | '/admin/student-management'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/bluej.vue': {
      routes:
        | '/bluej'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/coding_standard.vue': {
      routes:
        | '/coding_standard'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/course-resource.vue': {
      routes:
        | '/course-resource'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/courses.vue': {
      routes:
        | '/courses'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/graph-sketcher.vue': {
      routes:
        | '/graph-sketcher'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ide.vue': {
      routes:
        | '/ide'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/pathways.vue': {
      routes:
        | '/pathways'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/payment.vue': {
      routes:
        | '/payment'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/profile.vue': {
      routes:
        | '/profile'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/python-ide.vue': {
      routes:
        | '/python-ide'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/README.vue': {
      routes:
        | '/README'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/reset-password.vue': {
      routes:
        | '/reset-password'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/signup.vue': {
      routes:
        | '/signup'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/teaching.vue': {
      routes:
        | '/teaching'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/wheel.vue': {
      routes:
        | '/wheel'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/zelle.vue': {
      routes:
        | '/zelle'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/zoom.vue': {
      routes:
        | '/zoom'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
