/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module "vue-router/auto-routes" {
	import type {
		RouteRecordInfo,
		ParamValue,
		ParamValueOneOrMore,
		ParamValueZeroOrMore,
		ParamValueZeroOrOne
	} from "vue-router";

	/**
	 * Route name map generated by unplugin-vue-router
	 */
	export interface RouteNamedMap {
		"/": RouteRecordInfo<"/"	""/"
			"/",
			Record<never, never>,
			"/[...all]""/[...all]": "/[...all]">;
		In"/:all(.*)"all..",]
Record<never
			"/:all(.*)",
			{ all: ParamValue<true> },
			{ "/about"amValue<false> }
	"/about"ab"/about"uteRecordInfo<
			"/about",
			"/about",
			Recor"/profile"ever>,
			Record<n"/profile"r>"/profile"profile": RouteRecordInfo<
			"/profile",
			"/pr"/README"		Record<never, ne"/README"Re"/README"r, never>
		>;
		"/README": RouteRecordInfo<
			""/signup"
			"/README",
			"/signup"ve"/signup",
			Record<never, never>
		>;
		"/signup": Route"/supportus"			"/signup",
			""/supportus"	R"/supportus" never>,
			Record<never, never>
		>;
		"/supportus": RouteRecordInfo<
			"/supportus",
			"/supportus",
			Record<never, never>,
			Record<never, never>
		>;
	}
}
