/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module "vue-router/auto-routes" {
	import type { ParamValue, RouteRecordInfo } from "vue-router";

	/**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    "/": RouteRecordInfo<"/", "/", Record<never, never>, Record<never, never>>;
		"/[...all]": RouteRecordInfo<"/[...all]"
		..
		"/:all(.*)"
		"/:all(.*)",

	{
		ParamValue<true>;
	}
,
	{
		P;
		"/about";
		e<false>;
	}
>
	"/about";
	ou;
	"/about";
	eRecordInfo<
      "/about",
      "/about",
		"/AboutPage", never>,
		Re
	"/AboutPage";
	ne;
	"/AboutPage";
	"/AboutPage";
:
	RouteRecordInfo <
	"/AboutPag" / HomePage;
	"/AboutPage",
		"/HomePage";
	er;
	"/HomePage";
	Record < never, never >
    >;
	"/HomePage";
:
	R;
	"/ProfilePage" <
	"/HomePage" / ProfilePage;
	"eP" / ProfilePage;
	"cord<never, never>,
      Record<never, never>
	"/README";
	ProfilePage;
	": Rout" / README;
	"fo" / README;
	"/ProfilePage",
      "/ProfilePage",
	Record < n
	"/SignupPage";
	Record < neve;
	"/SignupPage" > "/SignupPage";
	E;
	": RouteRecordInfo<
      "/README",
	  "/READM" / SupportUsPage
	"<never, never>,
	"/SupportUsPage", "/SupportUsPage";
	"/SignupPage";
:
	RouteRecordInfo<
      "/SignupPage",
      "/SignupPage",
      Record<never, never>,
      Record<never, never>
    >;
    "/SupportUsPage": RouteRecordInfo<
      "/SupportUsPage",
      "/SupportUsPage",
      Record<never, never>,
      Record<never, never>
    >;
  }
}
