/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module "vue-router/auto-routes" {
	import type { ParamValue, RouteRecordInfo } from "vue-router";
	
	
	/**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
		"/": RouteRecordInfo<"/", "/", Record<never, never>, Record<never, never>>,
		"/[...all]": RouteRecordInfo<"/[...all]", "/:all(.*)", { all: ParamValue<true> }, { all: ParamValue<false> }>,
		"/about": RouteRecordInfo<"/about", "/about", Record<never, never>, Record<never, never>>,
		"/AboutPage": RouteRecordInfo<"/AboutPage", "/AboutPage", Record<never, never>, Record<never, never>>,
		"/hi/[name]": RouteRecordInfo<"/hi/[name]", "/hi/:name", { name: ParamValue<true> }, {
			name: ParamValue<false>
		}>,
		"/HomePage": RouteRecordInfo<"/HomePage", "/HomePage", Record<never, never>, Record<never, never>>,
		"/ProfilePage": RouteRecordInfo<"/ProfilePage", "/ProfilePage", Record<never, never>, Record<never, never>>,
		"/README": RouteRecordInfo<"/README", "/README", Record<never, never>, Record<never, never>>,
		"/SignupPage": RouteRecordInfo<"/SignupPage", "/SignupPage", Record<never, never>, Record<never, never>>,
		"/SupportUsPage": RouteRecordInfo<"/SupportUsPage", "/SupportUsPage", Record<never, never>, Record<never, never>>,
  }
}
